config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :locations do
		resources :recordings
	end
	root "locations#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :recordings, dependent: :destroy
	belongs_to :user
end

app/models/recording.rb
class Recording < ApplicationRecord
	belongs_to :location
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :locations, dependent: :destroy
  has_many :recordings, dependent: :destroy

  validates :name, presence: true, length:{maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permited_params, if: :devise_controller?
  
  protected
  	def configure_permited_params
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :get_loc, only: [:destroy, :show, :edit, :update]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@locations = Location.all.order('Created_at DESC')
	end

	def new
		@location = Location.new
	end

	def edit
	end
	  
	def update
	  	if @location.update(loc_params)
	    	redirect_to @location
	    else
	    	render 'edit'
	   	end
	end

	def destroy
	    @location.destroy
	    redirect_to locations_path
	end

	def show
	end

	def create
	    @location = current_user.locations.new(loc_params)
	    @location.save
	    redirect_to @location
	end

	private
		def get_loc
			@location = Location.find(params[:id])
		end
		def loc_params
      		params.require(:location).permit(:name)
    	end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
	before_action :authenticate_user!

	def create
	   	@location = Location.find(params[:location_id])
	   	@recording = @location.recordings.create(rec_params)
	   	@recording.user_id = current_user.id if current_user
	   	@recording.save
		redirect_to location_path(@location)

  	end
  
  private
  def rec_params
     params.require(:recording).permit(:temp, :status, :user_id) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Examen1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <div>
      <%= render 'partials/messages' %>
      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/locations/_form.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= bootstrap_form_for @location do |f| %>
		  <div class="field">
			  <%= f.text_field :name %>
		  </div>
		  <p><%= f.submit "Comfirm!", class: "btn btn-success" %></p>
		<% end %>	
	</div>
</div>

app/views/locations/edit.html.erb
<h1 class="text-center">Edit Location</h1>

<%= render 'form' %>

app/views/locations/index.html.erb
<div class="row">
	<div class="col-md-7 col-md-offset-2">
		<% @locations.each do |location| %>
		    <h2><%= link_to location.name, location %></h2>
		    <p><%= location.created_at.strftime("%B, %d, %Y") %></p>
		<% end %>
	</div>
</div>

app/views/locations/new.html.erb
<h1 class="text-center">New Location</h1>

<%= render 'form' %>

app/views/locations/show.html.erb
<div class="row">
	<div class="col-md-7 col-md-offset-2">
		<h1><%= @location.name %></h1>
		<p>
		    Location registered <%= time_ago_in_words(@location.created_at) %> Ago

		    <% if(user_signed_in? && current_user.id == @location.user_id) %>
			  | <%= link_to "Edit", edit_location_path(@location) %> 
			  | <%= link_to "Delete", location_path(@location), method: :delete, 
			        data: {confirm: 'Are you sure?'} %>
		    <% end %>
		</p>
		<div>
			<h5><%= @location.recordings.count %> Recordings</h5>
			<hr>
			<%= render @location.recordings %>
			<h6>Add a recording</h6>
			<%= render 'recordings/form' %>
		</div>
	</div>
</div>

app/views/partials/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
 <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Clima", root_path, class: "navbar-brand" %>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "All Locations", root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "New Location", new_location_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%=current_user.name%> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#"><%= link_to "Edit User", edit_user_registration_path%></a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#"><%= link_to "Sign out", destroy_user_session_path, method: :delete%></a></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path%></li>
            <li><%= link_to "Sign In", new_user_session_path%></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/recordings/_form.html.erb
<%= bootstrap_form_for([@location, @location.recordings.build]) do |f| %>
  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.text_field :temp, class: "form-control" %>
      </div>
    </div>
    
    <div class="col-md-9">
      <div class="field">
        <%= f.text_area :status, class: "form-control" %>
      </div>
    </div>
  </div>
  <span class="pull-right">
    <%= f.submit "Save recording", class: "btn btn-success" %>
  </span>
<% end %>

app/views/recordings/_recording.html.erb
<div class="well">
  <b>Temperature: </b> <%= recording.temp%> degrees. <b>Status: </b><%= recording.status %>
  <span class="pull-right"> <b>Recorded:</b> <%= recording.created_at.strftime("%H:%M:%S, %d/%m/%y") %></span>
</div>